# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Moca - Architecte & Décoratrice
email: moulin.caroline.a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Moca - Architecte & Décoratrice basée à Montpellier.
#baseurl: ""
baseurl: "https://mocabycarolinemoulin.github.io/moca/"
#baseurl: "http://ingeniousgeorge.com/moca"
#baseurl: "file:///run/user/1000/gvfs/sftp:host=devraj.local,user=jc/home/jc/Sites/Link_to_moca-master/_site" # the subpath of your site, e.g. /blog
url: "https://mocabycarolinemoulin.github.io/moca/" # the base hostname & protocol for your site
permalink: /:title
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
